---
- hosts: master
  become: yes
  tasks:
    - name: Initialize the cluster
      shell: kubeadm config images pull

    - name: Initialize the cluster
      shell: kubeadm init --pod-network-cidr=192.168.0.0/16 >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: Create .kube directory
      become: yes
      become_user: aida
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: Copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/aida/.kube/config
        remote_src: yes
        owner: aida

    - name: Install Pod network (Tigera Operator Calico)
      become: yes
      become_user: aida
      shell: kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml >> pod_network_calico.txt
      args:
        chdir: $HOME
        creates: pod_network_calico.txt

    - name: Install Pod network (Tigera Operator Custom resource)
      become: yes
      become_user: aida
      shell: kubectl create -f https://docs.projectcalico.org/manifests/custom-resources.yaml >> pod_network_resource.txt
      args:
        chdir: $HOME
        creates: pod_network_resource.txt