apiVersion: v1
kind: Service
metadata:
  name: demo-flask-svc
  namespace: uc1
  labels:
    app: demo-flask-svc
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
    - port: 4000
      targetPort: 5000
      nodePort: 30101
      name: flask-port

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: demo-flask-app
  namespace: uc1
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: demo-flask-app
          image: usman476/demo-flask-app:latest
          #command: [ "python3" ]
          #args: [ "app.py" ]
          command: [ "flask" ]
          args: [ "run", "-h", "0.0.0.0", "-p", "5000" ]
          #command: [ "opentelemetry-instrument" ]
          #args: [ "--traces_exporter", "jaeger_thrift", "flask", "run" ]
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          imagePullPolicy: "Always"
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: worker1