---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kc-nm-deployment
  namespace: observability
  labels:
    app: kafka-consumer-observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer-observability
  template:
    metadata:
      labels:
        app: kafka-consumer-observability
    spec:
      containers:
      - name: kc-nm-container
        image: usman476/kafka-consumer-metrics:latest
        imagePullPolicy: "Always"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        volumeMounts:
          - mountPath: /metrics
            name: test-volume
      volumes:
        - name: test-volume
          hostPath:
            # directory location on host
            path: /opt/observability/metrics
            # this field is optional
            type: Directory
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: observability1
