---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kc-nm-deployment
  namespace: monitoring
  labels:
    app: kafka-consumer-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer-monitoring
  template:
    metadata:
      labels:
        app: kafka-consumer-monitoring
    spec:
      containers:
      - name: kc-nm-container
        image: usman476/kafka-consumer-metrics:latest
        imagePullPolicy: "IfNotPresent"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: observability-vm-1