apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: collectd-node-metrics
  namespace: measurement
  labels:
    environment: production
    k8s-app: collectd-measurement
spec:
  selector:
    matchLabels:
      name: collectd-node-metrics
  template:
    metadata:
      labels:
        name: collectd-node-metrics
    spec:
      tolerations:
      # this toleration is to have the daemonset runnable on master nodes
      # remove it if your masters can't run pods
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: collectd-node-metrics
        image: usman476/aida-collectd:latest
        imagePullPolicy: "IfNotPresent"
        env:
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
#        resources:
#          limits:
#            memory: 200Mi
#          requests:
#            cpu: 100m
#            memory: 200Mi
#        volumeMounts:
#        - name: varlog
#          mountPath: /var/log
#        - name: varlibdockercontainers
#          mountPath: /var/lib/docker/containers
#          readOnly: true
      terminationGracePeriodSeconds: 10