---
- hosts: master
  become: yes
  gather_facts: false
  tasks:
    - name: Creates certs config directory
      become: yes
      file:
        path: /certs
        state: directory
        mode: '0777'
        recurse: yes

    - name: Set Host IP address
      set_fact:
        target_ip: "{{ ansible_ssh_host }}"

    - name: Change the IP address in the san.cnf file
      lineinfile:
        path: kubernetes-dashboard/san.cnf
        regexp: '^IP.1    = "Kubernetes master IP"$'
        insertafter: '^\s*\[alt_names\]\s*$'
        line: "IP.1    = {{ target_ip }}"

    - name: Print host's ip address
      debug:
        msg: "{{ ansible_ssh_host }}"

    - name: Create openssl key file
      shell: openssl req -out /certs/dashboard.csr -newkey rsa:2048 -nodes -keyout /certs/dashboard.key -config kubernetes-dashboard/san.cnf

    - name: Create certificate file
      shell: openssl x509 -req -sha256 -days 3650 -in /certs/dashboard.csr -signkey /certs/dashboard.key -out /certs/dashboard.crt -extensions req_ext -extfile kubernetes-dashboard/san.cnf

    - name: Changes certs config directory permissions
      file:
        path: /certs
        state: directory
        mode: '0777'
        recurse: yes

- hosts: master
  become: yes
  tasks:
    - name: Deploy Kubernetes Dashboard Resources on the Master Node
      kubernetes.core.k8s:
        kubeconfig: "{{ kubernetes_config_path }}"
        state: present
        src: "{{ playbook_dir }}/kubernetes-dashboard/kubernetes-dashboard.yml"

    - name: Create Kubernetes Dashboard Service Account
      kubernetes.core.k8s:
        kubeconfig: "{{ kubernetes_config_path }}"
        state: present
        src: "{{ playbook_dir }}/kubernetes-dashboard/serviceaccount.yml"

    - name: Create Kubernetes Dashboard RBAC
      kubernetes.core.k8s:
        kubeconfig: "{{ kubernetes_config_path }}"
        state: present
        src: "{{ playbook_dir }}/kubernetes-dashboard/rbac.yml"

    - name: List Kubernetes Dashboard Pods
      shell: kubectl get po -n kubernetes-dashboard