---
- hosts: workers
  become: yes
  gather_facts: false
  tasks:
    - name: Creates certs config directory
      file:
        path: /certs
        state: directory
        mode: '0777'
        recurse: yes

    - name: Copying files to the remote server
      copy:
        src: "{{ item }}"
        dest: /home/aida
        owner: aida
        group: aida
        mode: 0777
      with_fileglob:
        - kubernetes-dashboard/kubernetes-dashboard.yml
        - kubernetes-dashboard/serviceaccount.yml
        - kubernetes-dashboard/rbac.yml
        - kubernetes-dashboard/san.cnf

    - name: Set join command
      set_fact:
        target_ip: "{{ ansible_ssh_host }}"

    - name: Change the IP address
      lineinfile:
        path: san.cnf
        regexp: '^IP.1    = "Kubernetes master IP"$'
        insertafter: '^\s*\[alt_names\]\s*$'
        line: "IP.1    = {{ target_ip }}"

    - name: Show host's ip
      debug:
        msg: "{{ ansible_ssh_host }}"

    - name: Create openssl key file
      shell: openssl req -out /certs/dashboard.csr -newkey rsa:2048 -nodes -keyout /certs/dashboard.key -config san.cnf

    - name: Create certificate file
      shell: openssl x509 -req -sha256 -days 3650 -in /certs/dashboard.csr -signkey /certs/dashboard.key -out /certs/dashboard.crt -extensions req_ext -extfile san.cnf

    - name: Changes certs config directory permissions
      file:
        path: /certs
        state: directory
        mode: '0777'
        recurse: yes

    - name: Create Kubernetes resources
      shell: |    
        kubectl apply -f kubernetes-dashboard/kubernetes-dashboard.yml
        kubectl apply -f kubernetes-dashboard/serviceaccount.yml
        kubectl apply -f kubernetes-dashboard/rbac.yml

    - name: List kubernetes resources
      shell: kubectl get po -n kubernetes-dashboard