apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-pv-1
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/kafka
  claimRef:
    namespace: observability
    name: data-bitnami-zookeeper-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: appstype
          operator: In
          values:
          - observability

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/kafka
  claimRef:
    namespace: observability
    name: data-bitnami-kafka-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: appstype
          operator: In
          values:
          - observability

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/prometheus
  claimRef:
    namespace: observability
    name: prometheus-server
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: appstype
          operator: In
          values:
          - observability

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/elasticsearch
  claimRef:
    namespace: observability
    name: es-master-es-master-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: appstype
          operator: In
          values:
          - observability

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-pv-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/loki
  claimRef:
    namespace: observability
    name: storage-loki-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: appstype
          operator: In
          values:
          - observability

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-pv-read-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/loki
  claimRef:
    namespace: observability
    name: data-loki-read-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: appstype
          operator: In
          values:
          - observability

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-pv-write-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/loki
  claimRef:
    namespace: observability
    name: data-loki-write-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: appstype
          operator: In
          values:
          - observability

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv-1
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/grafana
  claimRef:
    namespace: observability
    name: grafana
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: appstype
          operator: In
          values:
          - observability