---
apiVersion: v1
kind: Namespace
metadata:
  name: measurement

---
apiVersion: v1
kind: Namespace
metadata:
  name: delivery

---
apiVersion: v1
kind: Namespace
metadata:
  name: connect

---
apiVersion: v1
kind: Namespace
metadata:
  name: fusion

---
apiVersion: v1
kind: Namespace
metadata:
  name: store

---
apiVersion: v1
kind: Namespace
metadata:
  name: visualization