---
- hosts: master
  become: yes
  tasks:
    - name: Create .kube directory
      become: yes
      become_user: aida
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: Copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: $HOME/.kube/config
        remote_src: yes
        owner: aida

    - name: Get the token for joining the worker nodes
      become: yes
      become_user: aida
      shell: kubeadm token create  --print-join-command
      register: kubernetes_join_command

    - debug:
      msg: "{{ kubernetes_join_command.stdout }}"

    - name: Copy join command to local file.
      become: yes
      local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777