---
- hosts: master
  tasks:
    - name: Create .kube directory
      become: true
      become_user: "{{ ansible_user }}"
      file:
        path: "{{ ansible_user_dir }}/.kube"
        state: directory
        mode: 0755

    - name: Copy admin.conf to user's kube config
      become: yes
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "{{ ansible_user_dir }}/.kube/config"
        remote_src: yes
        owner: "{{ ansible_user }}"

    - name: Get the token for joining the worker nodes
      become: yes
      become_user: "{{ ansible_user }}"
      shell: kubeadm token create  --print-join-command
      register: kubernetes_join_command

    - name: Print join command
      ansible.builtin.debug:
        msg: "{{ kubernetes_join_command.stdout }}"

    - name: Copy join command to local file.
      become: yes
      local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777