---
- hosts: master
  become: yes
  vars:
    API_SERVER_IP: "{{ ansible_ssh_host }}"
    API_SERVER_PORT: 6443
  tasks:
    - name: Add Cilium Helm repo
      kubernetes.core.helm_repository:
        name: cilium
        repo_url: "https://helm.cilium.io/"

    - name: Install Cilium CNI using Helm
      kubernetes.core.helm:
        kubeconfig: /home/aida/.kube/config
        name: cilium
        chart_ref: cilium/cilium
        chart_version: 1.13.0
        release_namespace: kube-system
        values:
          kubeProxyReplacement: strict
          k8sServiceHost: "{{ API_SERVER_IP }}"
          k8sServicePort: "{{ API_SERVER_PORT }}"

    - name: Wait for Cilium Pods to be ready
      shell: sleep 30

    - name: Enable UI and Relay for Cilium using Helm
      become: yes
      become_user: aida
      shell: helm upgrade cilium cilium/cilium --version 1.13.0 --namespace kube-system --reuse-values --set hubble.relay.enabled=true --set hubble.ui.enabled=true --set hubble.ui.service.type=NodePort

#    - name: install Pod network
#      become: yes
#      become_user: aida
#      shell: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.txt
#      args:
#        chdir: $HOME
#        creates: pod_network_setup.txt

#    - name: Enable kube-proxy, if needed (e.g., in case disabled when creating cluster and later want to deploy a CNI with flannel)
#      become: yes
#      shell: kubeadm init phase addon kube-proxy  --kubeconfig ~/.kube/config
