---
- hosts: master
  become: yes
  gather_facts: true
  vars:
    install_deps_master: true
  tasks:
    - include_tasks: install-dependencies-master.yaml
      when: install_deps_master

- hosts: observability
  become: yes
  gather_facts: true
  vars:
    install_deps_obs_server: true
  tasks:
    - include_tasks: install-dependencies-obs-server.yaml
      when: install_deps_obs_server

- hosts: master
  gather_facts: true
  vars:
    kubernetes_config_path: /home/aida/.kube/config
    install_kafka: false
    install_rabbitmq: false
    install_elasticsearch: false
    install_grafana: false
    install_prometheus: false
    install_loki: false
    install_jaeger: false
    install_telegraf: false
    install_promtail: false
    install_kc_nm: false
  tasks:
    - include_tasks: create-kubernetes-objects.yaml

    - include_tasks: install-delivery-services.yaml

    - include_tasks: install-storage-services.yaml

    - include_tasks: install-visualization-services.yaml

    - include_tasks: install-fusion-services.yaml

    - include_tasks: install-measurement-services.yaml