---
apiVersion: v1
kind: Pod
metadata:
  name: collectd-node-metrics
  labels:
    environment: production
    app: collectd-node-metrics-svc
spec:
  containers:
  - name: collectd-node-metrics-container
    image: usman476/aida-collectd:latest
    env:
      - name: HOSTNAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
    imagePullPolicy: "IfNotPresent"
  restartPolicy: OnFailure
  nodeSelector:
    kubernetes.io/hostname: observability-vm-1