kind: Pod
apiVersion: v1
metadata:
  name: demo-cassandra-app
spec:
  containers:
    - name: demo-cassandra-app
      image: usman476/demo-cassandra-app:latest
      command: [ "python3" ]
      args: [ "app.py" ]
      #command: [ "sleep" ]
      #args: [ "1800" ]
      #command: [ "opentelemetry-instrument" ]
      #args: [ "--traces_exporter", "jaeger_thrift", "flask", "run" ]
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "512Mi"
          cpu: "500m"
      imagePullPolicy: "Always"
      #command: ["/bin/bash", "-ec", "while :; do echo '.'; sleep 5 ; done"]
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/hostname: worker1
