---
apiVersion: v1
kind: Pod
metadata:
  name: mqtt-subscriber-pod
  namespace: uc0
  labels:
    environment: production
    app: mqtt-subscriber-pod
spec:
  containers:
  - name: mqtt-subscriber-container
    image: usman476/mqtt-subscriber:latest
    imagePullPolicy: "IfNotPresent"
  restartPolicy: Always
  nodeSelector:
    kubernetes.io/hostname: worker-vm-2